### ISSUE TITLE
merge configuration items

### ISSUE THREAD

**Issue by rocky114** [actiontech/dms#74]
merge the configuration file database_driver_options.yaml

**Comment by rocky114** [comment]
升级需要将原配置文件database_driver_option.yaml内容移动到config.yaml，如：
```yaml
database_driver_options:
    - db_type: MySQL
      logo_path: "/logo/mysql.png"
      params:
```
